"""initial call record

Revision ID: 61195ba9919f
Revises: 
Created: 2026-07-30 22:18:03.672304+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '61195ba9919f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('caller_phone_last4', sa.String(length=8), nullable=True),
    sa.Column('caller_name', sa.String(length=120), nullable=True),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('stt_model', sa.String(length=80), nullable=True),
    sa.Column('tts_model', sa.String(length=80), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('latency_p50_ms', sa.Float(), nullable=True),
    sa.Column('latency_p95_ms', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('handed_off', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calls_started_at', 'calls', ['started_at'], unique=False)
    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('claimed_by', sa.String(length=120), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoffs_call_id'), 'handoffs', ['call_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('reservation_id', sa.String(length=64), nullable=True),
    sa.Column('confirmation_code', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_call_id'), 'tool_calls', ['call_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_confirmation_code'), 'tool_calls', ['confirmation_code'], unique=False)
    op.create_index(op.f('ix_tool_calls_reservation_id'), 'tool_calls', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_status'), 'tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool'), 'tool_calls', ['tool'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('interrupted', sa.Boolean(), nullable=False),
    sa.Column('e2e_ms', sa.Float(), nullable=True),
    sa.Column('eou_ms', sa.Float(), nullable=True),
    sa.Column('llm_ttft_ms', sa.Float(), nullable=True),
    sa.Column('tts_ttfb_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_call_id'), 'turns', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_call_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_tool_calls_tool'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_status'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_reservation_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_confirmation_code'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_call_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_handoffs_call_id'), table_name='handoffs')
    op.drop_table('handoffs')
    op.drop_index('ix_calls_started_at', table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
